### ISSUE TITLE
Issue plotting burst summary 

### ISSUE THREAD

**Issue by apoorva6262** [bycycle-tools/bycycle#111]
Hi @ryanhammonds ,

I have been trying identify waveform features within bursts for my eeg epoched file. And I used the neurodsp tool as well to identify the number and duration of bursts. Now, I am trying to incorporate the bycycle tool to identify the same number of bursts as I did earlier using neurodsp. I am extracting two channels of interest and calculating waveform features. However, by using neurodsp I get 91 bursts and with bycycle I get 71 bursts. Of course, the type of filter and 'threshold' used are different in bycycle which is possibly detecting a different number of bursts. But is there an example that combines neurodsp and bycycle tool ? That would be helpful. 

Also, when plotting on bycycle using 'plot_burst_detect_summary' , I do not see the red colored burst in my plot.  I am not sure why the peak and troughs are not all getting detecting. And then when I 'plot plot_feature_hist' for the df_channels, it only plots one histogram (output attached). 

 

 Below is my code that I used: 

`picks = ['C3','C4']  # epochs_set.ch_names
signal=epoch_set.get_data(picks=picks)
signal=np.swapaxes(signal,0,1) 

Fs=2000
f_beta=(13,30)

thresholds = dict(amp_fraction_threshold=0.2, amp_consistency_threshold=.5,
                  period_consistency_threshold=.8, monotonicity_threshold=.6,
                  min_n_cycles=3)

# Merge epochs into a single dataframe
n_channels,n_epochs,n_times=signal.shape

compute_kwargs = {'burst_method': 'cycles', 'threshold_kwargs': thresholds,'return_samples': True}

df = compute_features_3d(signal, Fs, f_beta, compute_kwargs)

# Merge channels into a single dataframe
labels = [f'{picks[ch_idx]} {ep_idx}'
             for ch_idx in range(n_channels)
             for ep_idx in range(n_epochs)]

df_channels = flatten_dfs(df, labels, 'Channel')

# Limit to bursts
df_channels = df_channels[df_channels['is_burst'] == True]
print(f'Number of bursts found: {len(df_channels)}')

plot_burst_detect_summary(df[0][0], signal[0,2], Fs, thresholds,
                           figsize=(4, 1))

fig, axes = plt.subplots(figsize=(15, 15), nrows=2, ncols=2)
plot_feature_hist(df_channels, 'time_rdsym', ax=axes[1][0], xlim=(0, 1), color='k',
                  xlabel='Rise-decay asymmetry\n(fraction of cycle in rise period)',
                  bins=np.arange(0, 1, .02))`

<img width="909" alt="Screenshot 2021-08-19 at 12 53 54" src="https://user-images.githubusercontent.com/76274425/130135249-58717b96-302b-4799-93a3-0aea32731920.png">
<img width="921" alt="Screenshot 2021-08-19 at 12 55 58" src="https://user-images.githubusercontent.com/76274425/130135431-781da4e6-030f-45b2-a71e-526949700c0d.png">

<img width="654" alt="Screenshot 2021-08-19 at 12 56 53" src="https://user-images.githubusercontent.com/76274425/130135663-9eac65aa-45ca-4074-9eb1-6641a0ebf57c.png">

**Comment by ryanhammonds** [comment]
Hi @apoorva6262, there isn't a tutorial/example for this yet, but dual threshold method from neurodsp is available as an option in bycycle with the `burst_method='amp'` argument.

```python
from neurodsp.sim import sim_bursty_oscillation
from neurodsp.burst import detect_bursts_dual_threshold
from neurodsp.plts import plot_bursts

from bycycle.features import compute_features
from bycycle.plts import plot_burst_detect_summary

n_seconds = 10
fs = 1000
f_range = (1, 100)

sig = sim_bursty_oscillation(n_seconds, fs, freq=20, phase='min')

burst_kwargs = {'amp_threshes': (1, 2), 'min_n_cycles': .01}

threshold_kwargs = {'burst_fraction_threshold': .5}

df = compute_features(sig, fs, f_range, burst_method='amp', burst_kwargs=burst_kwargs,
                      threshold_kwargs=threshold_kwargs)

plot_burst_detect_summary(df, sig, fs, threshold_kwargs=threshold_kwargs)
```

There doesn't seem to be any bursts in the first second of this signal. If you inspect the spectrum of this signal or parameterize with fooof, is there an increase in beta power?

The other histograms aren't being plotted, because additional plot calls are required if you want to plot more than just rise-decay symmetry. See the example [here](https://bycycle-tools.github.io/bycycle/auto_examples/plot_2_mne_feature_distributions.html#plot-feature-distributions).

**Comment by apoorva6262** [comment]
Thanks for the example @ryanhammonds . Is there a way to calculate the mean burst duration as well on bycycle ? like something similar to 'compute_burst_stats' ? 

I have attached the spectrum for two channels(c3 and c4) (generated with mne and 'power_spectra' from fooof), there seems to be something in lower beta. But then how is it that it still shows that 71 bursts are detected when there are none showing on the plot ? 
<img width="606" alt="Screenshot 2021-08-19 at 16 36 22" src="https://user-images.githubusercontent.com/76274425/130157912-0cfe20ea-96f0-4181-80ea-11326617f944.png">
<img width="660" alt="Screenshot 2021-08-19 at 16 36 59" src="https://user-images.githubusercontent.com/76274425/130157915-332f6263-7f29-4160-9c4a-2638bc000c6f.png">

**Comment by apoorva6262** [comment]
I am still figuring out how use fooof

**Comment by apoorva6262** [comment]
Also I am getting this error 
"compute_features_3d() got an unexpected keyword argument 'burst_method'"

**Comment by apoorva6262** [comment]
@ryanhammonds , one other issue I came across is that when I use compute features 3d and plot it, the plot displays 1s data only which is 1 epoch of 1s. But the file is a lot longer (>200s) . I am not sure if it is a MNE issue or bycycle issue.

**Comment by ryanhammonds** [comment]
@apoorva6262, bycycle doesn't have a burst stats function. But you could use the df to make an `is_burst` boolean array to pass to neurodsp's compute_burst_stats:
```python
import numpy as np
from neurodsp.burst import compute_burst_stats

is_burst = np.zeros(len(sig), dtype='bool')

df_burst = df[df['is_burst'] == True]

last_troughs = df_burst['sample_last_trough'].values
next_troughs = df_burst['sample_next_trough'].values

for last_trough, next_trough in zip(last_troughs, next_troughs):
    is_burst[last_trough:next_trough] = True
    
compute_burst_stats(is_burst, fs)
```

If you df has burst that aren't being plotted, is the `xlim` argument set to `(0, 1)`? That may be why it's not plotting the full signal and bursts are not shown. If that's not it, then I could help further debug if you could provide an example array / bycycle settings you're using. 

The unexpected kwarg errors should be resolved if burst_method and burst_kwargs are passed together in a dict to compute_features_3d.

```python
compute_kwargs = {
    'burst_method': 'amp',
    'burst_kwargs': {'amp_threshes': (1, 2), 'min_n_cycles': .01}
}

features = compute_features_3d(sigs, fs, f_range=(8, 12), compute_features_kwargs=compute_kwargs)
```

**Comment by apoorva6262** [comment]
Thanks @ryanhammonds ,

I tried to run compute_burst_stats and I am getting this error. This happened earlier too when using neurodsp only for certain files (although all files were preprocessed the same way). 

<img width="846" alt="Screenshot 2021-08-20 at 12 19 24" src="https://user-images.githubusercontent.com/76274425/130283461-b0d200ea-a2bc-4ceb-a76a-cfd32d53b9e6.png">

**Comment by apoorva6262** [comment]
I am getting another error when using  `burst_method` in compute_kwargs, and plotting it using `plot_burst_detect_summary(df_features, sig, fs, threshold_kwargs=compute_kwargs) `  

 KeyError: 'burst_method'

**Comment by ryanhammonds** [comment]
The first error is because there aren't any burst detected, if `is_burst.any()` returns `False`, then this is the case.

The second error is because  `compute_kwargs` from my last comment shouldn't be passed to the plot function. Here is an example that highlights the difference between the two sets of kwargs:
```python
import numpy as np
from neurodsp.sim import sim_bursty_oscillation

from bycycle.group import compute_features_3d
from bycycle.plts import plot_burst_detect_summary

fs = 500
sigs = np.array([[sim_bursty_oscillation(10, fs, freq=10) for epoch in range(3)]
                for ch in range(2)])

threshold_kwargs = {'amp_consistency_threshold': .5, 'period_consistency_threshold': .5,
                    'monotonicity_threshold': .8, 'min_n_cycles': 3}
compute_kwargs = {'threshold_kwargs': threshold_kwargs, 'center_extrema': 'trough'}

features = compute_features_3d(sigs, fs, f_range= (8, 12),
                               compute_features_kwargs=compute_kwargs)

plot_burst_detect_summary(features[0][0], sigs[0][0], fs, threshold_kwargs)
```

**Comment by apoorva6262** [comment]
For the first error , there are bursts detected, so I am not sure what's happening.
`df_channels = df_channels[df_channels['is_burst'] == True]
print(f'Number of bursts found: {len(df_channels)}')`

This displays 293 bursts for the file I am using.

**Comment by apoorva6262** [comment]
Thank you, but it is still plotting for 1s. Not sure why...
<img width="809" alt="Screenshot 2021-08-20 at 14 37 46" src="https://user-images.githubusercontent.com/76274425/130297073-bcbda58a-d1a5-4abb-b2e5-db123a852fa3.png">

**Comment by apoorva6262** [comment]
Here is my code, I am wondering why it displays 0 bursts using compute_stats but if you look at the table you can see that there are many bursts ( is_burst = True)  : 

```
#Load file , filter, pick channels of interest
epoch_set=mne.io.read_epochs_eeglab('file.set')
epoch_set.filter(l_freq=14, h_freq=30)
picks = ['C3','C4']  # epochs_set.ch_names
signal=epoch_set.get_data(picks=picks)
signal=np.swapaxes(signal,0,1)

Fs=2000
f_beta=(14,30)

# Merge epochs into a single dataframe
n_channels,n_epochs,n_times=signal.shape


threshold_kwargs = {'burst_fraction_threshold': .1}

compute_kwargs = {
    'burst_method': 'amp',
    'burst_kwargs': {'amp_threshes': (1, 2), 'min_n_cycles': 3}
}


df = compute_features_3d(signal, Fs, f_beta, compute_features_kwargs=compute_kwargs)


plot_burst_detect_summary(df[0][0], signal[0,0], Fs, threshold_kwargs=threshold_kwargs,
                           #figsize=(4, 1))

is_burst = np.zeros(len(signal), dtype='bool')

# Merge channels into a single dataframe
labels = [f'{picks[ch_idx]} {ep_idx}'
             for ch_idx in range(n_channels)
             for ep_idx in range(n_epochs)]

df_channels = flatten_dfs(df, labels, 'Channel')

# Limit to bursts
df_ch = df_channels[df_channels['is_burst'] == True]
print(f'Number of bursts found: {len(df_ch)}')

last_troughs = df_ch['sample_last_trough'].values
next_troughs = df_ch['sample_next_trough'].values

for last_trough, next_trough in zip(last_troughs, next_troughs):
    is_burst[last_trough:next_trough] = True
    
compute_burst_stats(is_burst, Fs)

```

Output : 


<img width="695" alt="Screenshot 2021-08-20 at 15 25 15" src="https://user-images.githubusercontent.com/76274425/130299080-f008b0af-90f6-4122-bb24-00cfdea1fb54.png">

<img width="839" alt="Screenshot 2021-08-20 at 15 21 22" src="https://user-images.githubusercontent.com/76274425/130299090-5cfa7134-6ddd-4a4a-9f2b-1f60c64412c6.png">

<img width="534" alt="Screenshot 2021-08-20 at 15 31 08" src="https://user-images.githubusercontent.com/76274425/130299461-9485423c-5964-4b1c-a4ad-5a2fe5757669.png">

**Comment by apoorva6262** [comment]
Also is there a way to use 'min_burst_duration' in kwargs instead of 'burst_fraction_threshold' like in neurodsp?  

Since I already filtered my signal before computing_features, is there a way I can avoid filtering twice like in `compute_features_3d(signal, Fs, f_range, compute_features_kwargs=compute_kwargs)`   ?  I know in neurodsp you can set 'min_burst_duration' and that way you can set f_range=None . I tried setting f_range=None in compute_features_3d , but that gave me an error.

**Comment by ryanhammonds** [comment]
This line `print(f'Number of bursts found: {len(df_ch)}')` is printing the number of cycles, not the number of bursts, since several cycles make up a single bursts. 

Another issue is this line `is_burst = np.zeros(len(signal), dtype='bool')`. The signal is 3d, the len(signal) won't be equal to the correct number of samples per 1d signal. I adapted your code with simulated data:

```python
import numpy as np

from neurodsp.sim import sim_bursty_oscillation
from neurodsp.burst import compute_burst_stats

from bycycle.group import compute_features_3d
from bycycle.plts import plot_burst_detect_summary
from bycycle.utils import flatten_dfs

# Simulate a 3d signal
Fs = 1000
n_epochs = 5
n_channels = 5

np.random.seed(0)
signal = np.array([[sim_bursty_oscillation(10, Fs, freq=10, phase='min') for epoch in range(n_epochs)]
                for ch in range(n_channels)])

threshold_kwargs = {'burst_fraction_threshold': .8}

compute_kwargs = {
    'burst_method': 'amp',
    'burst_kwargs': {'amp_threshes': (.1, .5), 'min_n_cycles': 2},
    'threshold_kwargs': threshold_kwargs
}

f_beta = (12, 20)

df = compute_features_3d(signal, Fs, f_beta, compute_features_kwargs=compute_kwargs)

plot_burst_detect_summary(df[0][0], signal[0,0], Fs, threshold_kwargs=threshold_kwargs)

# Merge channels into a single dataframe
labels = [f'{ch_idx} {ep_idx}'
             for ch_idx in range(n_channels)
             for ep_idx in range(n_epochs)]

df_channels = flatten_dfs(df, labels, 'Channel')

# Limit to bursts
is_burst = np.zeros(len(signal[0][0]), dtype='bool')

df_ch = df[0][0]
df_ch = df_ch[df_ch['is_burst'] == True]

print(f'Number of bursts found: {len(df_ch)}')

last_troughs = df_ch['sample_last_trough'].values
next_troughs = df_ch['sample_next_trough'].values

for last_trough, next_trough in zip(last_troughs, next_troughs):
    is_burst[last_trough:next_trough] = True
    
compute_burst_stats(is_burst, Fs)
```
Out:

> Number of bursts found: 63

> {'n_bursts': 11,
>  'duration_mean': 0.47263636363636363,
>  'duration_std': 0.28049542946439115,
>  'percent_burst': 51.99,
>  'bursts_per_second': 1.1}


Also, I'd recommend install neurodsp/bycycle from github main branches too. (git clone, cd into clone, pip install -e .) There have been plotting bug fixes since the last pypi release.

Currently, `min_burst_duration` isn't an available option in bycycle. This would be a nice future update. The dual amp option in bycycle has a lesser used alternative - and this PR has led me to find strange behavior / bugs when using this option. Next week I'm going to start a round of updates fixing the bugs I've found.

The second filter in bycycle is necessary to find cyclepoints (peaks/troughs/mids) based on the f_range of interest. The actual shape/burst measured in the dataframe, however, are based on the original signal passed into compute_features.

**Comment by apoorva6262** [comment]
Thank you. Since we are using burst_method as 'amp', the min_n_cycles in `'burst_kwargs': {'amp_threshes': (.1, .5), 'min_n_cycles': 2}` does not matter right ? Because for neurodsp, you do not account for number of cycles right ? 

And I ran the updated code and got this as my output , I am really skeptical that even with the lowest dual threshold it is only detecting 1 burst. Is it possibly accounting for 1 epoch only ? at least that's what the plot looks like  : 

 
{'n_bursts': 1,
 'duration_mean': 0.9325,
 'duration_std': 0.0,
 'percent_burst': 93.25,
 'bursts_per_second': 1.0}


<img width="649" alt="Screenshot 2021-08-20 at 20 26 54" src="https://user-images.githubusercontent.com/76274425/130309007-8bb8abe2-8817-46d6-bb36-f92ed69d26f6.png">

**Comment by apoorva6262** [comment]
@ryanhammonds,  does bycycle have office hours or is it possible to zoom chat so that I can show my data file and it maybe easier to debug ? Lmk

**Comment by ryanhammonds** [comment]
Hi @apoorva6262, my email is rhammonds@ucsd.edu if you'd like to schedule a zoom call this week to discuss your data/analysis.

**Comment by apoorva6262** [comment]
> Hi @apoorva6262, my email is [rhammonds@ucsd.edu](mailto:rhammonds@ucsd.edu) if you'd like to schedule a zoom call this week to discuss your data/analysis.

Great, sent an email!
