### ISSUE TITLE
bycycle.filt moved?

### ISSUE THREAD

**Issue by dvwz** [bycycle-tools/bycycle#130]
Hi all,

In another version of this repo, there might have been a bycycle.filt that is referenced in some previous analysis done by our lab. Has it been moved or removed?

Thanks,
David

**Comment by ryanhammonds** [comment]
Filtering has been left to the neurodsp dependency. Here is the filter function that bycycle uses now:

https://neurodsp-tools.github.io/neurodsp/generated/neurodsp.filt.filter_signal.html?highlight=filter_signal#neurodsp.filt.filter_signal
