### ISSUE TITLE
Conda install version `1.0.0` not compatible with `BycycleGroup` tutorials

### ISSUE THREAD

**Issue by ntolley** [bycycle-tools/bycycle#135]
Just came across the issue that some of the tutorials are not compatible `1.0.0` release distributed on the conda repository. Specifically it looks like the `BycycleGroup` class wasn't added until `1.1.0` so it throws an import error. pip install works fine of course!

**Comment by ryanhammonds** [comment]
I merged this [PR](https://github.com/conda-forge/bycycle-feedstock/pull/2) that may have fixed the issue? I don't use conda but lmk if it doesn't fix the install.

**Comment by ntolley** [comment]
Yeah that updated the version! Can confirm the import passes after testing locally.

Also related to the same tutorial, it seems like there's a variable that doesn't get used [here](https://github.com/bycycle-tools/bycycle/blob/44c995d06fcd2e746fd4e1955d35f4a69c64fbaf/tutorials/plot_5_3D_sigs.py#L116)

I can try revising it in a PR if you guys are are cool with it! I'm guessing it should be something like:
```py
compute_kwargs = {'burst_method': 'cycles', 'thresholds': thresholds}
bg_rest = BycycleGroup(**compute_kwargs)
```
?

**Comment by ryanhammonds** [comment]
@ntolley I can review a PR for this is you want to make one. Thanks!
