### ISSUE TITLE
amplitude threshold burst detection with cycle discretization does not work for trough-centered cycles

### ISSUE THREAD

**Issue by srcole** [bycycle-tools/bycycle#23]
`burst.detect_bursts_df_amp` could be easily modified to work for peak-to-peak cycles.

`'sample_last_trough'` is hard coded, but the code could just determine which extrema are the centers and sides.

**Comment by ryanhammonds** [comment]
This was completed in #63 in the `compute_burst_fraction` function of `bycycle.features.burst`, the diff is [here](https://github.com/bycycle-tools/bycycle/commit/2f808d6c1e69fb4edb00c70cd5539eee173915f5#diff-f5fbbf164dcccddb72598cae9f78c3fal).
