### ISSUE TITLE
Move talk to it's own repository?

### ISSUE THREAD

**Issue by TomDonoghue** [bycycle-tools/bycycle#30]
Right now there is a branch on here that includes a talk, that was presented a SfN. 

Instead of having it on a branch (which I think is harder to find), now that we have an organization for everything ByCycle, why don't we move the talk to it's own repository, which could collect and store any code-driven talks?

Example with FOOOF:
https://github.com/fooof-tools/presentations

**Comment by srcole** [comment]
good call

**Comment by srcole** [comment]
https://github.com/bycycle-tools/presentations
