### ISSUE TITLE
crash when sampling frequency is a float

### ISSUE THREAD

**Issue by nschawor** [bycycle-tools/bycycle#36]
Hi, thanks for fixing the transition band issue, very helpful!

In contrast to the previous version, the current github version now crashes with "TypeError: exceptions must derive from BaseException" when the sampling frequency is a float (which should not be the case anyway, but maybe a more helpful warning could be shown instead then). 

Minimal working example:
```
import numpy as np
from bycycle.features import compute_features

Fs = 250.
f_alpha = (8, 12)
signal = np.random.randn(10000,)
df = compute_features(signal, Fs=Fs, f_range=f_alpha)
```

**Comment by srcole** [comment]
i checked it out, and it's beyond me how that bit of code fails when Fs is a float ;)
I just forced it to be an int in the last PR

**Comment by nschawor** [comment]
thank you Scott!
