### ISSUE TITLE
documentation for some cycle features is missing

### ISSUE THREAD

**Issue by nschawor** [bycycle-tools/bycycle#38]
(just for completeness) 
Here: https://bycycle-tools.github.io/bycycle/generated/bycycle.features.compute_features.html

For these ones:
- 'amp_fraction', 
- 'amp_consistency', 
- 'period_consistency',
- 'monotonicity'

**Comment by ryanhammonds** [comment]
Hi @nschawor, I added  documentation for these in #51. I defined these from the bycycle publication. If these definitions look good to you, I can merge and rebuild the site.

**Comment by TomDonoghue** [comment]
merged in #51
