### ISSUE TITLE
"f_range" is a mandatory input for the compute_features function

### ISSUE THREAD

**Issue by ShuangquanFeng** [bycycle-tools/bycycle#41]
"f_range" is a mandatory input for the compute_features function and the bandpass filter is a mandatory procedure. I know that the edge artifacts should be relatively trivial while comparing long time continuous signals  (e.g. general brain signals of patients and healthy people), but we are analyzing multiple segments of short time signals of 3 seconds length time locked to a particular event, so the edge artifacts exist in every trial and may result in non-trivial distortion of the signal. Is there any way to skip the bandpass filtering procedure?

**Comment by nschawor** [comment]
I think the easiest way in your situation would be to cut the signal into epochs of longer length (so more signal around the edges), run the cycle detection and then restrict the cycles to the time window of interest again. That should work out fine. bycycle automatically discards the cycles which would be affected by filter edge effects (for these, the ```df.is_burst```-value is always ```False```).

I would say one can only skip the band-pass filtering for very high signal-to-noise ratio for sustained oscillations, and this is (almost) never the case for neural oscillations. :slightly_smiling_face:
