### ISSUE TITLE
Modularize  bycycle.burst.detect_bursts_cycles

### ISSUE THREAD

**Issue by nschawor** [bycycle-tools/bycycle#46]
It would be desirable to compute the ```df.is_burst``` column without having to supply the data for easier hyperparameter tuning as well as to recompute this column when dealing with epoched data. 

This computation is performed within the ```burst.detect_bursts_cycles``` function, which takes the burst features dataframe as well as the data vector ```x```.  The data is needed to compute monotonicity, but it could be done in ```features.compute_features``` or further modularized somewhere else, so ```burst.detect_bursts_cycles``` does not require ```x``` as a parameter anymore. This would simplifying rerunning this function, without having to load the data along with the dataframe.

**Comment by ryanhammonds** [comment]
This was complete in  #63. `df['is_burst']` can now be recomputed using `bycycle.burst.cycle.detect_bursts_cycles`. It doesn't require supplying the signal, only the dataframe and thresholds.

`features.compute_features` has been modularized and consists of:
1) `compute_cyclepoints`: compute the sample indices (`df_samples`) of cyclepoints.
2) `compute_shape_features`: uses `df_samples` to compute `df_shape_features` (period, time_peak, volt_peak, time_rdsym, band_amp, etc).
3) `compute_burst_features`: uses `df_shape_features`to compute `df_burst_features`, which are cycle features used to identify bursts (monotonicity, amp_consistency, etc).
