### ISSUE TITLE
ModuleNotFoundError: No module named 'bycycle.filt'

### ISSUE THREAD

**Issue by ethanrich** [bycycle-tools/bycycle#71]
Hello,

I installed the master branch and when trying the examples, my local doesn't contain "filt" from which to import `lowpass_filter`. Am I missing something?

**Comment by ryanhammonds** [comment]
Hi @ethanrich, bycycle is currently undergoing a refactor and the filt submodule has been replaced by imports from neurodsp. The current documentation corresponds to v.0.1.3 (https://github.com/bycycle-tools/bycycle/tree/0.1.3) or the pypi release. The documentation will be updated soon. Sorry for the confusion!
