### ISSUE TITLE
reduce size of example data files

### ISSUE THREAD

**Issue by TomDonoghue** [bycycle-tools/bycycle#81]
The data files in `examples/data/` are pretty big files (~47 MB each). These big files make the repo needlessly big to clone / download, etc. 

From a quick check, we only use these files once, in the `plot_theta_feature_distributions` example. Within that example, we immediately extract 1 second of data (about 1% of the length), so most of this data isn't even used in the example. 

Basically, we should trim and replace the data files and only package the 1 second segments in `examples/data/`. 

@ryanhammonds - can you double check if these files are used anywhere else? If not, please make the minimized data files, and replace in `examples`. 

Sidenote: I wouldn't be opposed to keeping a collection of some bigger datafiles that are used for examples / testing, etc - but if so, these could be put in a separate place / repo (`bycycle-tools/Data`, for example), to still keep the code repo as small.

**Comment by ryanhammonds** [comment]
Complete in #82.
