### ISSUE TITLE
NaN values for band_amp

### ISSUE THREAD

**Issue by rahul-jayaram1** [bycycle-tools/bycycle#96]
Hello, 

When I am running cycle-by-cycle to obtain band_amp values, some of the values seem to be NaN rather than float values. I was wondering if you could help me understand how exactly the band_amp values are calculated for each cycle, and this might help me resolve this issue. Thank you!

**Comment by ryanhammonds** [comment]
Hi @rahul-jayaram1, band_amp is determined from a filtered signal and I believe older versions of bycycle would replace values at the filter edges with np.nan. Are you using the latest pypi release or main branch? If updating doesn't help or you already are using the latest version, I can better help with a small piece of reproducible code. I tried testing this with simulated signals and band_amp was never nan.

**Comment by rahul-jayaram1** [comment]
Hello, 

Thank you for your prompt email! I will try using the latest pypi release and will let you know what happens. I also just wanted to clarify what exactly this feature is measuring? I’m not too familiar with the concept of analytic amplitude (and whether this is different from standard amplitude), and was hoping you could briefly help me understand this feature conceptually. 

Thank you for your help!

**Comment by ryanhammonds** [comment]
No problem! The analytic amplitude here is the instantaneous amplitude, or the absolute value of the hilbert transform of a filtered signal (red line below). The dataframe output provides the mean of this, per cycle.

![example](https://user-images.githubusercontent.com/34786005/110046607-30142d00-7d01-11eb-9286-8c6c358a246e.png)

**Comment by rahul-jayaram1** [comment]
Thank you! Is the filtered signal the bandpassed signal based on the frequency range we specified?

**Comment by ryanhammonds** [comment]
Yes, the `f_range` passed to `compute_features` is the same range of interest that gets passed to `compute_band_amp`.

**Comment by ryanhammonds** [comment]
Feel free to re-open if unresolved :smile:
